"""that should be all the migrations

Revision ID: 83730978c4c8
Revises: 59f9a31bc429
Create Date: 2021-09-14 23:55:13.271120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83730978c4c8'
down_revision = '59f9a31bc429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_title', sa.String(length=50), nullable=False),
    sa.Column('initial_data', sa.Text(), nullable=False),
    sa.Column('added_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('matrix_title', sa.String(length=50), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('matrix_id', sa.Integer(), nullable=True),
    sa.Column('generated', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output')
    op.drop_table('matrix')
    op.drop_table('sample')
    # ### end Alembic commands ###
